feat(mv3): Redirection Tests
ipfs-shipyard/ipfs-companion pull request #1236
Opened 2023-07-18 09:58 UTC by whizzzkid

Closes: #1235

In this PR:

- Adding support for MV3 specific interaction in Redirection Cycle.
- Tests:
  - https://github.com/ipfs/ipfs-companion/blob/rc/3.0-mv3/test/functional/lib/ipfs-request-gateway-redirect.test.js added MV3 equivalent
  - https://github.com/ipfs/ipfs-companion/blob/rc/3.0-mv3/test/functional/lib/ipfs-request-protocol-handlers.test.js added MV3 equivalent.
  - https://github.com/ipfs/ipfs-companion/blob/rc/3.0-mv3/test/functional/lib/ipfs-request-dnslink.test.js This only tests if the redirect did not happen and the tab got refreshed after, right now refresh happens momentarily after. https://github.com/ipfs/ipfs-companion/pull/1239 changes that to a message on the bus to tell when to refresh page, the tests will be added along with that.
  - https://github.com/ipfs/ipfs-companion/blob/rc/3.0-mv3/test/functional/lib/ipfs-request-gateway-recover.test.js similar interaction is already testest in redirect testing
  
  
Edit (during the review):
- Simplified setup to run tests both on MV2 and MV3.
- Added better `ensure..` methods to test for both MV2 and MV3 side-effects.
- DRYed and Refactored.

2023-07-20 14:49 UTC, lidel requested changes
@whizzzkid thank you, the direction is good, nearly there.

Dropped quick feedback below, ping me when I should make a proper pass on this (I did not look at all tests due to reasons below – will be more efficient to look after these nits are addressed)

2023-07-20 14:49 UTC, lidel commented on add-on/src/lib/redirect-handler/blockOrObserve.ts
> +export const supportsBlock = (): boolean => !(browser.declarativeNetRequest?.MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES === 5000)
nit: this check will break when Google changes limit.

Maybe:

```suggestion
export const noDeclarativeNetRequest = (): boolean => !(typeof browser.declarativeNetRequest === 'function')
```

?

2023-07-20 14:49 UTC, lidel commented on test/functional/lib/ipfs-request-gateway-redirect.test.mv3.js
Any reason why this is a separate file?
I would expect  `ipfs-request-gateway-redirect.test.js` to have tests for both MV2 and MV3, we will run into maintenance problems if we don't keep regression tests in sync.

If it is ok, move MV2 expects there and remove `.mv3.js` – wil be way way easier to review. :pray: 

(I did `diff ipfs-request-gateway-redirect.test.js ~/tmp/ipfs-request-gateway-redirect.test.mv3.js` and various tests are not present here, and I dont know if that was intentional, if we test them elsewhere, or what. By having a single file, it easier to ask these questions.  I think it is okay to have some things only tested for MV2 for now until we figure out how to test with MV3, or explicitly mark them as "this makes sense to be only tested for MV2")

2023-07-20 14:49 UTC, lidel commented on test/functional/lib/ipfs-request-protocol-handlers.test.mv3.js
Same here, this should be merged into `ipfs-request-protocol-handlers.test.js`

2023-07-21 20:43 UTC, lidel commented on test/functional/lib/ipfs-request-gateway-redirect.test.mv3.js
Hm.. no, we want to keep original MV2 tests as long we support blocking api.

I think having MV3 is separate file is better than not having it, if we don't solve it now, we will pay a higher price in maintenance but that is all. Don't want to block on this, we can figure out merging them later (or maybe it will not be relevant once firefox can switch to declarative API).

As for review or actual tests, I can do manual diff after you simplify code a bit (see note in https://github.com/ipfs/ipfs-companion/pull/1236#discussion_r1269564633) :pray:

2023-07-25 16:45 UTC, SgtPooki commented on test/functional/lib/ipfs-request-gateway-redirect.test.mv3.js
@whizzzkid another way we could do this is via environment variable that is read during the setup.. and we have the same file but just trigger a different browser.global setup, and have the tests pivot on running when that is set.

I can't remember if we tested that once we got the global setup abstracted out and things were working consistently.

2023-07-25 16:50 UTC, SgtPooki requested changes

2023-07-25 16:50 UTC, SgtPooki commented on test/setup/mocha-setup.js
> +}
merge two setup files and wrap execution of either on env-var?

2023-07-25 16:56 UTC, SgtPooki commented
@whizzzkid note that CI tests are emitting an error: https://github.com/ipfs/ipfs-companion/actions/runs/5597804498/job/15162779434?pr=1236#step:11:97

2023-07-25 20:03 UTC, SgtPooki commented
Ok. I made some updates, so maintenance of tests should be a lot easier (addressing most of @lidel and my concerns). 

https://github.com/ipfs/ipfs-companion/pull/1247 merges into https://github.com/ipfs/ipfs-companion/pull/1246 which merges into https://github.com/ipfs/ipfs-companion/pull/1236

2023-07-26 13:22 UTC, lidel commented on add-on/src/lib/redirect-handler/blockOrObserve.ts
> +export const supportsBlock = (): boolean => !(browser.declarativeNetRequest?.MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES === 5000)
oof, given [Google lost interest in MV3](https://groups.google.com/u/0/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E) that is not getting fixed any time soon.

Maybe at least remove dependency on specific number?

```suggestion
export const supportsBlock = (): boolean => !(browser.declarativeNetRequest?.MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES > 0)
```

2023-07-26 14:08 UTC, lidel requested changes

2023-07-27 20:28 UTC, SgtPooki commented on test/functional/lib/ipfs-request-gateway-redirect.test.js
> +          }
@lidel these were just me getting mv3 testing migrated from the two separate files to the same file, and not wanting to block on fixing all the individual tests that @whizzzkid has more context on.

2023-07-27 20:29 UTC, SgtPooki commented
@whizzzkid lmk when this is ready for me to peek at again!

2023-07-28 00:09 UTC, SgtPooki reviewed
looks like two tests from blockOrObserve.test.ts were removed? other than that.. it's looking good to me. just some comments and questions.

2023-07-28 00:09 UTC, SgtPooki commented on test/functional/lib/ipfs-request-gateway-redirect.test.js
>        })
@lidel @whizzzkid how deep does the maintenance for older versions go? We should be thinking about dropping support for extremely old versions if it's causing any issues. We can also check version numbers at https://github.com/plprobelab/network-measurements/blob/master/reports/2023/calendar-week-29/ipfs/README.md#agent-versions

2023-07-28 00:09 UTC, SgtPooki commented on test/functional/lib/redirect-handler/blockOrObserve.test.ts
> -    it('Should remove the old rules when companion is no longer in active state', async () => {
it looks like this test was removed? was that intentional?

2023-07-28 00:09 UTC, SgtPooki commented on test/functional/lib/redirect-handler/blockOrObserve.test.ts
> -    it('Should remove the old rule when redirect changes for local gateway', async () => {
it looks like this test was removed? was that intentional?

2023-07-28 17:59 UTC, SgtPooki approved these changes

2023-08-03 13:48 UTC, lidel requested changes
Thanks, made another pass,  and I think there are only a few  blockers:

- handling of `#fragment` (some rules preserve it, some do not?)
- greedy localhost and 0.0.0.0 rules without port
- cosmetic: improve UX of `ensureCallRedirected`

Details inline.

For the rest, I've filled separate issues for follow-up work that is not blocking this PR.

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-gateway-redirect.test.js
> +            destination: 'http://localhost:8080/ipfs/bafybeigfejjsuq5im5c3w3t3krsiytszhfdc4v5myltcg4myv2n2w6jumy'
:warning:  Not blocking this PR, but see https://github.com/ipfs/ipfs-companion/issues/1255 for follow-up work.

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-gateway-redirect.test.js
> +            // this is set as a default rule in MV3
Can we add a test for that? `DEFAULT_LOCAL_RULES` seems to be only used in `reconcileRulesAndRemoveOld` so maybe add unit test for that?

(Not blocker, ok to fill issue and do it as followup)

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-gateway-redirect.test.js
> +              destination: 'http://127.0.0.1'
:warning: iiuc  rules like this are too greedy and will break people's developer environments as they may run other things on different port.

Can we make the rule more specific, and add rule that touches only  the RPC port?

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-protocol-handlers.test.js
> +              destination: 'https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?argTest#'
Why is `#` included in `destination`? 

I was under the impression that declarative API rules do not include `#fragments`, and that the browser will append `#hashTest`  to the destination on its own.

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-protocol-handlers.test.js
> +              destination: 'https://ipfs.io/ipns/ipfs.io?argTest#'
:warning:  Not blocking this PR, but see https://github.com/ipfs/ipfs-companion/issues/1254 for follow-up work.

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-protocol-handlers.test.js
> +              destination: 'https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?arg=foo&bar=buzz#hash'
Test includes `#hash` here but i've seen skipped  `#hashTest` in some previous ones? 
This inconsistency looks like a bug that needs to be fixed in this PR.

- if declarative API takes care of `#fragments` then we should not include them in created rules.
- if it does not handle fragments, we need to preserve them somehow

2023-08-03 13:48 UTC, lidel commented on test/functional/lib/ipfs-request-workarounds.test.js
> +          destination: 'http://127.0.0.1:8080'
:warning:  Not blocking this PR, but please see https://github.com/ipfs/ipfs-companion/issues/1253 for follow-up work.

2023-08-25 20:35 UTC, lidel commented on test/helpers/mv3-test-helper.ts
> +  }))
`onBeforeRequest` and `onHeadersReceived` are expected to be called on a request in the [specific order](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest). 

I remember we had some edge cases where we woudl detect something in one stage, and act on it in other stage. One I remember is `ignoredRequests`, but there may be more (or we may add them in future). Better to do this sequentially.

2023-08-25 20:51 UTC, lidel commented on test/functional/lib/ipfs-request-protocol-handlers.test.js
> +              destination: 'https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?argTest#'
I think this is a bug in test.

The #fragment is not sent to the server when a URL is requested, as it's meant for client-side use, so we should remove it from `origin`:

```suggestion
              origin: '^https?\\:\\/\\/dweb\\.link\\/ipfs\\/\\?uri\\=ipfs%3A%2F%2FQmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR%3FargTes,
              destination: 'https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR?argTest'
```

2023-08-25 20:58 UTC, lidel commented on test/functional/lib/ipfs-request-gateway-redirect.test.js
> +            destination: 'http://127.0.0.1:8080'
Sgtm.

2023-08-27 08:54 UTC, merged