feat: remember manual opt-ins and opt-outs per site
ipfs-shipyard/ipfs-companion pull request #929
Opened 2020-10-15 03:03 UTC by lidel

This PR improves the way we handle manual opt-out performed per site by the user by storing both opt-out and opt-in decisions made by the user.

## Changes

### Explicit opt-in and opt-out lists in _Preferences_

- _Preferences_ screen now has separate list for opt-outs and opt-ins:
  > ![2020-10-15--04-48-21](https://user-images.githubusercontent.com/157609/96071073-b25e9a80-0ea1-11eb-986d-5fde11581774.png)
- In the past we only had opt-out list named `noIntegrationsHostnames`. 
  - Items from the old list are automatically migrated to the new one named `disabledOn`.
- If for some reason item is present on both lists, opt-out takes a priority.

### Menu toggle adds/moves hostname between lists

- The above lists can be modified by hand on _Preferences_ screen, 
  however the expectation is that most of the time users will not touch them. 
  - Instead, user will be toggling integrations for current website via browser action menu:
    > ![2020-10-15--04-34-22](https://user-images.githubusercontent.com/157609/96071185-df12b200-0ea1-11eb-9cb8-e4510d68fab4.png)

### Migrations can modify lists

- In this PR we are adding `proto.school` to opt-out list if it was not already present on either of lists.
  - This way we are able to tweak implicit default per website while respecting  preexisting user choices. 
  - Also, in the future we may run opt-in metrics  that compare lengths of both lists to gain better insight into user's behavior.
- [ ] TODO: confirm with Fleek that `app.fleek.co` should also be opt-out by default (does not work from local gateway atm)

Closes #921 cc @terichadbourne

2020-10-15 15:23 UTC, jsonsivar commented on add-on/src/lib/options.js
> +      'app.fleek.co' // TODO: confirm if ok
Janison from Fleek here - this looks good.  Thanks for this.  cc @studna

2020-10-15 19:26 UTC, jessicaschilling requested changes
Suggested some prefs text tweaks for clarity ...

2020-10-15 19:26 UTC, jessicaschilling commented on add-on/_locales/en/messages.json
> +    "message": "Manual Opt-Out List",
```suggestion
    "message": "Always Disable IPFS Integrations",
```

2020-10-15 19:26 UTC, jessicaschilling commented on add-on/_locales/en/messages.json
> +    "message": "Manual Opt-In List",
```suggestion
    "message": "Always Enable IPFS Integrations",
```

2020-10-15 19:26 UTC, jessicaschilling commented on add-on/_locales/en/messages.json
> +    "message": "Sites in this list (one hostname per line) will have IPFS integrations disabled.",
```suggestion
    "message": "Sites in this list (one URI or hostname per line) will always load with IPFS integrations disabled. Toggling \"Enable on ...\" from your browser's action menu while visiting a site will also add or remove it from this list.",
```

2020-10-15 19:26 UTC, jessicaschilling commented on add-on/_locales/en/messages.json
> +    "message": "Sites in this list (one hostname per line) will have IPFS integrations enabled.",
```suggestion
    "message": "Sites in this list (one URI or hostname per line) will always load with IPFS integrations enabled. Toggling \"Enable on ...\" from your browser's action menu while visiting a site will also add or remove it from this list.",
```

2020-10-15 20:13 UTC, lidel commented
@jessicaschilling merged your  suggestions, but removed "URI" from preference label [`853099b` (#929)](https://github.com/ipfs-shipyard/ipfs-companion/pull/929/commits/853099b15a2ea100e0ad85b62b83271658b6ff48) – we only support hostnames.  Would that be acceptable?

2020-10-15 20:42 UTC, jessicaschilling approved these changes
LGTM, thank you!

2020-10-16 13:39 UTC, lidel commented
I'm going to ship this to Beta soon, so we can dogfood it more, 
hopefully shipping to Stable next week.

2020-10-16 13:39 UTC, merged