fix: isHostname reports malformed IPv6 addresses as valid
ipfs-shipyard/ipfs-companion pull request #946
Opened 2020-11-27 19:06 UTC by Sierra410

Previous version of the function was reporting addresses like ``]::1[`` or even ``]:]:]1]`` as valid.

2020-11-27 19:34 UTC, jessicaschilling commented
@lidel - this is a follow-up from https://github.com/ipfs-shipyard/ipfs-companion/pull/945 - mind having a look? Thanks!

2020-11-28 00:13 UTC, lidel requested changes
@Sierra410 good catch! mind adding tests in https://github.com/ipfs-shipyard/ipfs-companion/blob/master/test/functional/lib/options.test.js#L64 with those false-positives?

2020-11-29 05:09 UTC, Sierra410 commented
Like this?

2020-11-30 13:31 UTC, lidel approved these changes
:+1:

2020-11-30 13:32 UTC, merged